"""baseline schema

Revision ID: 1260a22374d0
Revises: 
Create Date: 2026-04-25 00:21:06.832768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1260a22374d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_heartbeat_at')
    op.drop_column('jobs', 'execution_started_at')
    # ### end Alembic commands ###
