name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, infra]

    steps:
      - name: Deploy locally
        run: |
          cd ~/infra-learning
          ./deploy.sh
