name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, infra]

    steps:
      - name: Deploy locally
        run: |
          cd ~/infra-learning
          ./deploy.sh
